//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBackEnd.Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.UserSet = new HashSet<User>();
            this.ItemSet = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public int BusinessTypeId { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public int CityPostalCode { get; set; }
        public string CVR { get; set; }
        public int ChainId { get; set; }
    
        public virtual City CitySet { get; set; }
        public virtual BusinessType BusinessTypeSet { get; set; }
        public virtual Chain ChainSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> UserSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> ItemSet { get; set; }
    }
}
