//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBackEnd.Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public string ProcessName { get; set; }
        public string Page { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
        public int UserId { get; set; }
    
        public virtual User UserSet { get; set; }
    }
}
