//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBackEnd.Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemCampaignSet = new HashSet<ItemCampaign>();
            this.BusinessSet = new HashSet<Business>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImgURL { get; set; }
        public int BrandId { get; set; }
        public bool ProOnly { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
    
        public virtual Brand BrandSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCampaign> ItemCampaignSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Business> BusinessSet { get; set; }
    }
}
