//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBackEnd.Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCampaign
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int CampaignId { get; set; }
        public int Discount { get; set; }
        public string Description { get; set; }
    
        public virtual Campaign CampaignSet { get; set; }
        public virtual Item ItemSet { get; set; }
    }
}
